
const paragraphs=[
     "The sun was setting behind the distant mountains, casting long shadows across the valley. A gentle breeze rustled the leaves of the trees, creating a soothing melody. Birds chirped their evening songs as they returned to their nests. The scent of wildflowers filled the air, mingling with the earthy aroma of the forest floor. It was a peaceful scene, a moment of tranquility in a busy world.",
     "The moon cast a soft glow over the tranquil lake, shimmering gently on its surface. Trees swayed in the breeze, their leaves rustling in harmony with the night. A lone owl hooted in the distance, breaking the silence of the evening. Stars twinkled overhead, painting the sky with their brilliance. It was a peaceful night, a moment of quiet reflection under the vast expanse of the universe.", 
     "The quick brown fox jumps over the lazy dog. Jackdaws love my big sphinx of quartz. Mr. Jock, TV quiz PhD, bags few lynx. Sympathizing would fix Quaker objectives. Pack my box with five dozen liquor jugs. Sphinx of black quartz, judge my vow. The five boxing wizards jump quickly. How razorback-jumping frogs can level six piqued gymnasts.",
     "The quick brown fox jumps over the lazy dog, showcasing its agility and speed. A plethora of onlookers marvel at the graceful and swift movements of the fox as it effortlessly navigates the terrain. The dog, unfazed by the intrusion, lazily observes the scene, indifferent to the energetic display before it. The contrast between the two animals highlights the diverse nature of the animal kingdom, where each creature possesses unique traits and characteristics.",
     "The serene lake shimmered under the gentle caress of the setting sun, casting a mesmerizing array of colors across its tranquil surface. Tall trees stood sentinel along the water's edge, their branches swaying gently in the evening breeze. Nearby, a small rowboat bobbed lazily, its oars resting peacefully against its sides. As dusk descended, the sounds of nature filled the air, creating a symphony of chirping crickets and rustling leaves. It was a moment of pure serenity, where time seemed to stand still, allowing one to bask in the beauty of the natural world.",
     "In the heart of the bustling city, a symphony of sounds and sights unfolds. Skyscrapers reach for the sky, casting shadows on the busy streets below. Car horns and distant chatter create a cacophony of urban life, blending with the rhythmic footsteps of pedestrians. Neon lights illuminate storefronts, offering glimpses into a world of commerce and variety. Amidst the urban chaos, individuals weave through the crowded sidewalks, each with a unique destination and purpose.",
     "Amidst towering skyscrapers and bustling streets lies a quaint little cafe, drawing in patrons from all walks of life. Inside, the soothing melody of jazz music fills the air, creating a serene ambiance for those seeking refuge from the chaos outside. Baristas skillfully craft each cup with precision, their passion evident in every pour and swirl of milk. As customers chat animatedly over steaming cups of espresso and freshly baked pastries, time seems to stand still in this little oasis of tranquility.",
     "The old lighthouse stands tall against the backdrop of the stormy sea, its weathered exterior bearing witness to years of relentless waves crashing against its sturdy foundation. The beacon atop the tower emits a steady stream of light, guiding ships safely through the treacherous waters. Seagulls soar overhead, their cries echoing in the salty air as they ride the gusts of wind. Below, jagged rocks jut out from the tumultuous ocean, a reminder of the dangers lurking beneath the surface.",
     "An aunt is a bassoon from the right perspective. As far as we can estimate, some posit the melic myanmar to be less than kutcha. One cannot separate foods from blowzy bows. The scampish closet reveals itself as a sclerous llama to those who look. A hip is the skirt of a peak. Some hempy laundries are thought of simply as orchids. A gum is a trumpet from the right perspective. A freebie flight is a wrench of the mind. Some posit the croupy.",
     "The vision of an attempt becomes a lawny output. Dibbles are mis womens. The olden penalty reveals itself as a bustled field to those who look. Few can name a chalky force that isn't a primate literature. However, they were lost without the gamy screen that composed their beret. Nowhere is it disputed that a step-uncle is a factory from the right perspective. One cannot separate paints from dreary windows. What we don't know for sure is whether."
 ]
